@extends('layouts.app')
@section('title','Журнал · Админ')
@section('content')
<section class="page-top"><div class="container"><div class="eyebrow">Админ / журнал</div><h1 class="display-3 fw-bold">Электронный журнал</h1></div></section>
<section class="pb-5"><div class="container">
<form class="glass-card p-4 mb-4" method="get"><div class="row g-3"><div class="col-md-5"><label class="form-label">Группа</label><select class="form-select" name="group_id" onchange="this.form.submit()"><option value="">Выберите</option>@foreach($groups as $g)<option value="{{ $g->id }}" @selected(optional($group)->id===$g->id)>{{ $g->name }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Предмет</label><select class="form-select" name="subject_id"><option value="">Выберите</option>@if($group)@foreach($group->subjects as $s)<option value="{{ $s->id }}" @selected(optional($subject)->id===$s->id)>{{ $s->title }}</option>@endforeach @endif</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-neon w-100">Открыть</button></div></div></form>
@if($group && $subject)
<form class="glass-card p-4 mb-4" method="post" action="{{ route('admin.journal.lessons.create') }}">@csrf<input type="hidden" name="study_group_id" value="{{ $group->id }}"><input type="hidden" name="subject_id" value="{{ $subject->id }}"><div class="row g-3"><div class="col-md-3"><input type="date" class="form-control" name="lesson_date" required></div><div class="col-md-7"><input class="form-control" name="topic" placeholder="Тема урока" required></div><div class="col-md-2"><button class="btn btn-ghost w-100">+ Урок</button></div></div></form>
@foreach($lessons as $lesson)
<div class="glass-card p-4 mb-4"><h4>{{ $lesson->lesson_date->format('d.m.Y') }} · {{ $lesson->topic }}</h4><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Ученик</th><th>Посещение</th><th>Оценка</th><th>Комментарий</th><th></th></tr></thead><tbody>@foreach($group->students as $student)@php($entry=$lesson->entries->firstWhere('student_id',$student->id)) @if($entry)<tr><form method="post" action="{{ route('admin.journal.entries.update',$entry) }}">@csrf @method('PATCH')<td>{{ $student->name }}</td><td><select class="form-select form-select-sm" name="attendance">@foreach(['present'=>'Был','absent'=>'Отсутствовал','late'=>'Опоздал','excused'=>'Уваж. причина'] as $k=>$v)<option value="{{ $k }}" @selected($entry->attendance===$k)>{{ $v }}</option>@endforeach</select></td><td><input class="form-control form-control-sm" name="grade" type="number" min="1" max="100" step="0.01" value="{{ $entry->grade }}"></td><td><input class="form-control form-control-sm" name="comment" value="{{ $entry->comment }}"><input type="hidden" name="grade_label" value="{{ $entry->grade_label }}"></td><td><button class="btn btn-sm btn-ghost">Сохранить</button></td></form></tr>@endif @endforeach</tbody></table></div></div>
@endforeach
@endif
</div></section>
@endsection
