@extends('layouts.app')
@section('title','Админ-панель · ШКИ')
@section('content')
<section class="page-top"><div class="container"><div class="eyebrow">Control center</div><div class="d-flex justify-content-between align-items-end flex-wrap gap-3"><h1 class="display-2 fw-bold m-0">Админ-панель</h1><div class="d-flex gap-2 flex-wrap"><a href="{{ route('admin.studios.create') }}" class="btn btn-neon">+ Раздел</a><a href="{{ route('admin.news.create') }}" class="btn btn-ghost">+ Новость</a><a href="{{ route('admin.projects') }}" class="btn btn-ghost">Проекты</a><a href="{{ route('admin.events') }}" class="btn btn-ghost">События</a><a href="{{ route('admin.team') }}" class="btn btn-ghost">Команда</a><a href="{{ route('admin.equipment') }}" class="btn btn-ghost">Оборудование</a></div></div></div></section>
<section class="pb-5"><div class="container">
 <div class="glass-card p-4 mb-4"><div class="d-flex justify-content-between mb-3"><h3>Студии / разделы</h3><span class="text-white-50">{{ $studios->count() }} шт.</span></div><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Порядок</th><th>Название</th><th>Статус</th><th></th></tr></thead><tbody>@foreach($studios as $s)<tr><td>{{ $s->sort_order }}</td><td><strong>{{ $s->title }}</strong><div class="small text-white-50">/{{ $s->slug }}</div></td><td>{{ $s->is_active?'Активен':'Скрыт' }}</td><td class="text-end"><a class="btn btn-sm btn-ghost" href="{{ route('admin.media',$s) }}">Медиа</a> <a class="btn btn-sm btn-ghost" href="{{ route('admin.studios.edit',$s) }}">Изменить</a><form class="d-inline" method="post" action="{{ route('admin.studios.delete',$s) }}" onsubmit="return confirm('Удалить раздел?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">×</button></form></td></tr>@endforeach</tbody></table></div></div>
 <div class="glass-card p-4 mb-4"><h3 class="mb-3">Последние заявки</h3><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Дата</th><th>Имя</th><th>Контакты</th><th>Студия</th><th>Статус</th></tr></thead><tbody>@foreach($applications as $a)<tr><td>{{ $a->created_at->format('d.m.Y') }}</td><td>{{ $a->name }}</td><td>{{ $a->phone }}<div class="small text-white-50">{{ $a->email }}</div></td><td>{{ $a->studio->title ?? '—' }}</td><td><form method="post" action="{{ route('admin.applications.status',$a) }}">@csrf @method('PATCH')<select name="status" class="form-select form-select-sm" onchange="this.form.submit()">@foreach(['new'=>'Новая','processing'=>'В обработке','accepted'=>'Принята','rejected'=>'Отклонена'] as $k=>$v)<option value="{{ $k }}" @selected($a->status===$k)>{{ $v }}</option>@endforeach</select></form></td></tr>@endforeach</tbody></table></div></div>
 <div class="glass-card p-4"><h3 class="mb-3">Новости</h3>@foreach($news as $n)<div class="d-flex justify-content-between align-items-center py-3 border-bottom border-secondary-subtle"><div><strong>{{ $n->title }}</strong><div class="small text-white-50">{{ $n->is_published?'Опубликовано':'Черновик' }}</div></div><a href="{{ route('admin.news.edit',$n) }}" class="btn btn-sm btn-ghost">Редактировать</a></div>@endforeach</div>
</div></section>
@endsection
