@extends('layouts.app')
@section('title','Раздел · Админ')
@section('content')
<section class="page-top"><div class="container"><div class="eyebrow">Админ / разделы</div><h1 class="display-3 fw-bold">{{ $studio?'Редактировать':'Новый раздел' }}</h1></div></section>
<section class="pb-5"><div class="container"><form class="form-shell" method="post" enctype="multipart/form-data" action="{{ route('admin.studios.save',$studio) }}">@csrf
<div class="row g-3"><div class="col-md-8"><label class="form-label">Название</label><input class="form-control" name="title" value="{{ old('title',$studio->title ?? '') }}" required></div><div class="col-md-4"><label class="form-label">Slug</label><input class="form-control" name="slug" value="{{ old('slug',$studio->slug ?? '') }}"></div>
<div class="col-12"><label class="form-label">Подзаголовок</label><input class="form-control" name="subtitle" value="{{ old('subtitle',$studio->subtitle ?? '') }}"></div><div class="col-12"><label class="form-label">Описание</label><textarea class="form-control" rows="8" name="description">{{ old('description',$studio->description ?? '') }}</textarea></div>
<div class="col-md-3"><label class="form-label">Иконка/символ</label><input class="form-control" name="icon" value="{{ old('icon',$studio->icon ?? '✦') }}"></div><div class="col-md-3"><label class="form-label">Акцент</label><input type="color" class="form-control form-control-color w-100" name="accent" value="{{ old('accent',$studio->accent ?? '#8a5cff') }}"></div><div class="col-md-3"><label class="form-label">Порядок</label><input type="number" class="form-control" name="sort_order" value="{{ old('sort_order',$studio->sort_order ?? 0) }}"></div><div class="col-md-3 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$studio->is_active ?? true))><label class="form-check-label">Активен</label></div></div>
<div class="col-12"><label class="form-label">Обложка</label><input type="file" class="form-control" name="cover" accept="image/*"></div><div class="col-12 text-end"><button class="btn btn-neon btn-lg">Сохранить</button></div></div></form></div></section>
@endsection
